spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true

server:
  tomcat:
    redirect-context-root: false

logging:
  level:
    root: WARN
    com.yunesh.digitalwallet: INFO