spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_wallet_db
    username: postgres
    password: Himal123!
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 30000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    com.yunesh.digitalwallet: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"